function summaryTable = runAllGrbOdsSpotBeamCases(options)
%runAllGrbOdsSpotBeamCases Run and summarize every public GRB case.

arguments
    options.ProjectFolder (1,1) string = string(fileparts( ...
        mfilename("fullpath")))
    options.ResumeCompleted (1,1) logical = true
    options.DurationSeconds (1,1) double {mustBePositive} = 7200
    options.TimeStepSec (1,1) double {mustBePositive} = 2
    options.MonteCarloRuns (1,1) double {mustBeInteger,mustBePositive} = 4
    options.ZaRadiusKm double = []
    options.WriteDetailedTimeSeries (1,1) logical = true
end

projectFolder = options.ProjectFolder;
catalogFile = fullfile(projectFolder,"data","GRB_Receiver_Sites.csv");
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(projectFolder,fullfile(projectFolder,"config"), ...
    fullfile(projectFolder,"src"));
sites = loadGrbReceiverSites(catalogFile);
assert(height(sites) == 12,"ODS:AllRunCatalogCount", ...
    "The public all-case runner requires exactly 12 catalog rows.");

if isempty(options.ZaRadiusKm)
    zaRadiiKm = sites.DefaultZaRadiusKm;
else
    assert(all(isfinite(options.ZaRadiusKm)) && ...
        all(options.ZaRadiusKm >= 0),"ODS:AllRunZaValues", ...
        "Every ZA radius must be finite and nonnegative.");
    assert(isscalar(options.ZaRadiusKm) || ...
        numel(options.ZaRadiusKm) == height(sites),"ODS:AllRunZaCount", ...
        "ZaRadiusKm must be one scalar or one value per catalog row.");
    if isscalar(options.ZaRadiusKm)
        zaRadiiKm = repmat(options.ZaRadiusKm,height(sites),1);
    else
        zaRadiiKm = options.ZaRadiusKm(:);
    end
end

if isequal(zaRadiiKm,sites.DefaultZaRadiusKm)
    summaryName = "grb_ods_spot_beam_all_12_results.csv";
elseif all(zaRadiiKm == zaRadiiKm(1))
    zaToken = replace(string(sprintf("%.6g",zaRadiiKm(1))),".","p");
    summaryName = "grb_ods_spot_beam_all_12_results_za" + ...
        zaToken + "km.csv";
else
    summaryName = "grb_ods_spot_beam_all_12_results_za_custom.csv";
end
summaryFile = fullfile(projectFolder,summaryName);
summaryParts = cell(height(sites),1);

for caseIndex = 1:height(sites)
    site = table2struct(sites(caseIndex,:));
    zaRadiusKm = zaRadiiKm(caseIndex);
    expectedCfg = defaultGrbOdsSpotBeamConfig(site,projectFolder, ...
        projectFolder,zaRadiusKm);
    expectedCfg.simulation.duration = seconds(options.DurationSeconds);
    expectedCfg.simulation.timeStepSec = options.TimeStepSec;
    expectedCfg.simulation.monteCarloRuns = options.MonteCarloRuns;
    expectedCfg.output.writeDetailedTimeSeries = ...
        options.WriteDetailedTimeSeries;
    resultFile = fullfile(expectedCfg.output.folder,"ods_results.mat");
    useExisting = options.ResumeCompleted && isfile(resultFile);
    if useExisting
        loaded = load(resultFile,"results");
        results = loaded.results;
        useExisting = configurationMatches(results.config,expectedCfg);
    end

    fprintf("\n=== GRB ODS SPOT BEAM %d/%d: %s | %s | ZA %.6g km ===\n", ...
        caseIndex,height(sites),site.Name,site.Satellite,zaRadiusKm);
    caseTimer = tic;
    if useExisting
        fprintf("Reusing completed matching result: %s\n", ...
            expectedCfg.output.folder);
        resultSource = "resumed matching result";
    else
        results = runGrbOdsSpotBeamSimulator(site.SiteId, ...
            CatalogFile=catalogFile,OutputRoot=projectFolder, ...
            DurationSeconds=options.DurationSeconds, ...
            TimeStepSec=options.TimeStepSec, ...
            MonteCarloRuns=options.MonteCarloRuns, ...
            ZaRadiusKm=zaRadiusKm, ...
            WriteDetailedTimeSeries=options.WriteDetailedTimeSeries);
        resultSource = "new run";
    end
    elapsedSeconds = toc(caseTimer);
    assert(results.practical.feasible && ...
        results.practical.robustExceedancePercent <= 0.1 + 1e-12 && ...
        results.practical.robustAvailabilityPercent >= 99.9 - 1e-12 && ...
        results.practical.practicalPercentileIOverNDb <= -6 + 1e-12, ...
        "ODS:AllRunInfeasible", ...
        "No primary feasible angle pair for %s.",site.SiteId);
    summaryParts{caseIndex} = buildSummaryRow(sites(caseIndex,:), ...
        results,resultSource,elapsedSeconds);
    writetable(vertcat(summaryParts{1:caseIndex}),summaryFile);
end

summaryTable = vertcat(summaryParts{:});
fprintf("\nCompleted %d/%d cases. Summary: %s\n", ...
    height(summaryTable),height(sites),summaryFile);
clear pathCleanup
end

function tf = configurationMatches(saved,current)
tf = string(saved.meta.releaseId) == string(current.meta.releaseId) && ...
    string(saved.site.siteId) == string(current.site.siteId) && ...
    saved.za.protectedCoreRadiusKm == current.za.protectedCoreRadiusKm && ...
    saved.receiver.allowedExceedancePercent == ...
        current.receiver.allowedExceedancePercent && ...
    saved.antenna.farAngleGainDbiOverride == ...
        current.antenna.farAngleGainDbiOverride && ...
    seconds(saved.simulation.duration) == seconds(current.simulation.duration) && ...
    saved.simulation.timeStepSec == current.simulation.timeStepSec && ...
    saved.simulation.monteCarloRuns == current.simulation.monteCarloRuns;
end

function row = buildSummaryRow(siteRow,results,resultSource,elapsedSeconds)
row = table(siteRow.Index,siteRow.SiteId,siteRow.Name,siteRow.Satellite, ...
    results.config.antenna.diameterM,siteRow.FeedHeightM, ...
    results.config.za.protectedCoreRadiusKm, ...
    results.geometry.boresightElevationDeg, ...
    results.practical.outerAngleDeg,results.practical.innerAngleDeg, ...
    results.practical.robustExceedancePercent, ...
    results.practical.robustAvailabilityPercent, ...
    results.practical.practicalPercentileIOverNDb, ...
    results.practical.maximumIOverNDb, ...
    results.practical.retaskDutyPercent, ...
    results.practical.shutdownDutyPercent,results.practical.feasible, ...
    results.selected.outerAngleDeg,results.selected.innerAngleDeg, ...
    results.selected.worstExceedancePercent, ...
    results.selected.maximumIOverNDb,results.selected.feasible, ...
    string(resultSource),elapsedSeconds, ...
    VariableNames=["Index","SiteId","Site","Satellite", ...
    "ReceiverDiameterM","FeedHeightM","GeographicZaRadiusKm", ...
    "BoresightElevationDeg","OuterAngleDeg","InnerAngleDeg", ...
    "RobustExceedancePercent","RobustAvailabilityPercent", ...
    "Percentile99p9IOverNDb","MaximumIOverNDb", ...
    "RetaskDutyPercent","ShutdownDutyPercent","Feasible", ...
    "StrictOuterAngleDeg","StrictInnerAngleDeg", ...
    "StrictWorstExceedancePercent","StrictMaximumIOverNDb", ...
    "StrictFeasible","ResultSource","ElapsedSeconds"]);
end
