function verification = verifyGrbOdsSpotBeamSimulator(options)
%verifyGrbOdsSpotBeamSimulator Verify the public package and saved results.

arguments
    options.ProjectFolder (1,1) string = string(fileparts( ...
        mfilename("fullpath")))
    options.RequireAllResults (1,1) logical = true
end

projectFolder = options.ProjectFolder;
catalogFile = fullfile(projectFolder,"data","GRB_Receiver_Sites.csv");
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(projectFolder,fullfile(projectFolder,"config"), ...
    fullfile(projectFolder,"src"));
sites = loadGrbReceiverSites(catalogFile);
assert(height(sites) == 12,"ODS:CatalogRowCount", ...
    "The supplied catalog must contain exactly 12 cases.");

caseCount = height(sites);
verification = table(sites.Index,sites.SiteId,sites.Name,sites.Satellite, ...
    false(caseCount,1),false(caseCount,1),false(caseCount,1), ...
    false(caseCount,1),false(caseCount,1),false(caseCount,1), ...
    VariableNames=["Index","SiteId","Site","Satellite", ...
    "ConfigurationPassed","LookupPassed","ResultPresent", ...
    "ResultMetadataPassed","ResultCriterionPassed","AllPassed"]);

for caseIndex = 1:caseCount
    site = table2struct(sites(caseIndex,:));
    cfg = defaultGrbOdsSpotBeamConfig(site,projectFolder,projectFolder);
    validateOdsConfig(cfg);
    customZaKm = site.DefaultZaRadiusKm + 5;
    customCfg = defaultGrbOdsSpotBeamConfig(site,projectFolder, ...
        projectFolder,customZaKm);
    validateOdsConfig(customCfg);
    customZaPassed = ...
        customCfg.za.protectedCoreRadiusKm == customZaKm && ...
        customCfg.za.minimumActiveBeamCenterDistanceKm == customZaKm && ...
        customCfg.calibration.rampStartDistanceKm == customZaKm && ...
        endsWith(string(customCfg.output.folder), ...
            "_za" + string(customZaKm) + "km");
    verification.ConfigurationPassed(caseIndex) = ...
        string(cfg.meta.modelName) == "GRB ODS Spot Beam Simulator" && ...
        string(cfg.meta.releaseId) == ...
            "GRB-ODS-SPOT-BEAM-SIMULATOR-PUBLIC-1.0.0" && ...
        cfg.receiver.centerFrequencyHz == 1686.6e6 && ...
        cfg.receiver.bandwidthHz == 10.9e6 && ...
        cfg.receiver.noiseTemperatureK == 120 && ...
        cfg.antenna.diameterM == 4.5 && ...
        cfg.antenna.farAngleGainDbiOverride == -27 && ...
        cfg.beams.numberPerSatellite == 10 && ...
        cfg.beams.coneHalfAngleDeg == 60 && ...
        isequal(cfg.resources.protectedCarrierIndices,[2 3 4]) && ...
        isequal(cfg.resources.carrierOverlapBandwidthHz, ...
            [0 3.85e6 5e6 2.05e6]) && ...
        cfg.resources.maximumSimultaneousCochannelBeamsPerSatellite == 3 && ...
        cfg.rf.maximumBeamEirpDensityDbwPerMHz == 30 && ...
        cfg.za.protectedCoreRadiusKm == site.DefaultZaRadiusKm && ...
        cfg.ods.outerMinimumBeamCenterDistanceKm == 180 && ...
        cfg.receiver.protectionCriterionDb == -6 && ...
        cfg.receiver.allowedExceedancePercent == 0.1 && ...
        cfg.reporting.practicalAvailabilityPercent == 99.9 && ...
        cfg.site.minimumElevationDeg == 0 && customZaPassed && ...
        string(cfg.aggregation.selectionMode) == "allEligible" && ...
        string(cfg.aggregation.powerCombinationMode) == "linearSum" && ...
        seconds(cfg.simulation.duration) == 7200 && ...
        cfg.simulation.timeStepSec == 2 && ...
        cfg.simulation.monteCarloRuns == 4;
    verification.LookupPassed(caseIndex) = verifyLookup( ...
        cfg.propagation.atmosphericLookupFile);

    resultFolder = fullfile(projectFolder,"results_" + site.SiteId);
    resultFile = fullfile(resultFolder,"ods_results.mat");
    verification.ResultPresent(caseIndex) = isfile(resultFile);
    if verification.ResultPresent(caseIndex)
        loaded = load(resultFile,"results");
        results = loaded.results;
        verification.ResultMetadataPassed(caseIndex) = ...
            string(results.config.meta.releaseId) == ...
                "GRB-ODS-SPOT-BEAM-SIMULATOR-PUBLIC-1.0.0" && ...
            string(results.config.site.siteId) == site.SiteId && ...
            results.config.za.protectedCoreRadiusKm == ...
                site.DefaultZaRadiusKm && ...
            results.config.resources.maximumSimultaneousCochannelBeamsPerSatellite == 3 && ...
            isfile(fullfile(resultFolder,"grb_ods_angle_summary.csv")) && ...
            isfile(fullfile(resultFolder,"primary_selected_angles.csv")) && ...
            isfile(fullfile(resultFolder,"selected_angles.csv")) && ...
            isfile(fullfile(resultFolder,"configuration.json"));
        verification.ResultCriterionPassed(caseIndex) = ...
            results.practical.feasible && ...
            results.practical.innerAngleDeg <= ...
                results.practical.outerAngleDeg && ...
            results.practical.robustExceedancePercent <= 0.1 + 1e-12 && ...
            results.practical.robustAvailabilityPercent >= 99.9 - 1e-12 && ...
            results.practical.practicalPercentileIOverNDb <= -6 + 1e-12;
    end
end

if ~options.RequireAllResults
    verification.ResultPresent(:) = true;
    verification.ResultMetadataPassed(:) = true;
    verification.ResultCriterionPassed(:) = true;
end
verification.AllPassed = all(verification{:,5:9},2);
writetable(verification,fullfile(projectFolder, ...
    "grb_ods_spot_beam_verification.csv"));
assert(all(verification.AllPassed),"ODS:PackageVerification", ...
    "One or more public-package checks failed.");

summaryFile = fullfile(projectFolder, ...
    "grb_ods_spot_beam_all_12_results.csv");
if options.RequireAllResults
    assert(isfile(summaryFile),"ODS:MissingAllCaseSummary", ...
        "The all-case result summary is missing.");
    summary = readtable(summaryFile,TextType="string");
    assert(height(summary) == 12 && all(summary.Feasible) && ...
        all(summary.RobustExceedancePercent <= 0.1 + 1e-12) && ...
        all(summary.RobustAvailabilityPercent >= 99.9 - 1e-12) && ...
        all(summary.Percentile99p9IOverNDb <= -6 + 1e-12) && ...
        isequal(summary.SiteId,sites.SiteId), ...
        "ODS:InvalidAllCaseSummary", ...
        "The all-case result summary is incomplete or inconsistent.");
end
fprintf("GRB_ODS_SPOT_BEAM_SIMULATOR_VERIFY_PASS %d/%d cases passed.\n", ...
    nnz(verification.AllPassed),caseCount);
clear pathCleanup
end

function passed = verifyLookup(lookupFile)
passed = isfile(lookupFile);
if ~passed
    return
end
lookup = readtable(lookupFile);
required = ["ElevationDeg","GaseousLossDb","CloudLossDb", ...
    "RainLossDb","ScintillationLossDb","TotalAtmosphericLossDb"];
passed = height(lookup) == 86 && ...
    all(ismember(required,string(lookup.Properties.VariableNames))) && ...
    lookup.ElevationDeg(1) == 5 && lookup.ElevationDeg(end) == 90 && ...
    all(diff(lookup.ElevationDeg) > 0) && ...
    all(isfinite(lookup.TotalAtmosphericLossDb)) && ...
    all(lookup.TotalAtmosphericLossDb >= 0);
end
