function summaryTable = writeGrbOdsSummary(results,selectedSite)
%writeGrbOdsSummary Write the primary and diagnostic GRB result tables.

primary = table(results.practical.outerAngleDeg, ...
    results.practical.innerAngleDeg, ...
    results.practical.robustExceedancePercent, ...
    results.practical.robustAvailabilityPercent, ...
    results.practical.practicalPercentileIOverNDb, ...
    results.practical.maximumIOverNDb, ...
    results.practical.retaskDutyPercent, ...
    results.practical.shutdownDutyPercent,results.practical.feasible, ...
    VariableNames=["OuterAngleDeg","InnerAngleDeg", ...
    "RobustExceedancePercent","RobustAvailabilityPercent", ...
    "Percentile99p9IOverNDb","MaximumIOverNDb", ...
    "RetaskDutyPercent","ShutdownDutyPercent","Feasible"]);
writetable(primary,fullfile(results.config.output.folder, ...
    "primary_selected_angles.csv"));

summaryTable = table(string(results.config.meta.modelVersion), ...
    string(selectedSite.SiteId),string(selectedSite.Name), ...
    string(selectedSite.Satellite),selectedSite.LatitudeDeg, ...
    selectedSite.LongitudeDeg,selectedSite.BoresightLongitudeDeg, ...
    results.geometry.boresightElevationDeg,results.config.antenna.diameterM, ...
    results.config.receiver.noiseTemperatureK, ...
    results.config.antenna.farAngleGainDbiOverride, ...
    results.config.za.protectedCoreRadiusKm, ...
    results.practical.outerAngleDeg,results.practical.innerAngleDeg, ...
    results.practical.robustExceedancePercent, ...
    results.practical.robustAvailabilityPercent, ...
    results.practical.practicalPercentileIOverNDb, ...
    results.practical.maximumIOverNDb, ...
    results.practical.retaskDutyPercent, ...
    results.practical.shutdownDutyPercent,results.practical.feasible, ...
    results.selected.outerAngleDeg,results.selected.innerAngleDeg, ...
    results.selected.worstExceedancePercent, ...
    results.selected.maximumIOverNDb,results.selected.feasible, ...
    VariableNames=["ModelVersion","SiteId","Site","Satellite", ...
    "LatitudeDeg","LongitudeDeg","BoresightLongitudeDeg", ...
    "BoresightElevationDeg","ReceiverDiameterM", ...
    "ReceiverNoiseTemperatureK","FarAngleReceiveGainDbi", ...
    "GeographicZaRadiusKm","OuterAngleDeg","InnerAngleDeg", ...
    "RobustExceedancePercent","RobustAvailabilityPercent", ...
    "Percentile99p9IOverNDb","MaximumIOverNDb", ...
    "RetaskDutyPercent","ShutdownDutyPercent","Feasible", ...
    "StrictOuterAngleDeg","StrictInnerAngleDeg", ...
    "StrictWorstExceedancePercent","StrictMaximumIOverNDb", ...
    "StrictFeasible"]);
writetable(summaryTable,fullfile(results.config.output.folder, ...
    "grb_ods_angle_summary.csv"));
end
