function writeOdsResults(results, outputFolder)
%writeOdsResults Persist configuration and result tables.

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
save(fullfile(outputFolder, "ods_results.mat"), "results", "-v7.3");
writetable(results.searchTable, fullfile(outputFolder, "angle_search.csv"));

selected = rmfield(results.selected, ["time", "aggregateInterferenceDbm", ...
    "iOverNDb", "dominantSatelliteIndex", "visibleSatelliteCount", ...
    "candidateSatelliteCount", "effectiveContributorCount", ...
    "eligibleContributorCount"]);
summaryTable = struct2table(selected);
writetable(summaryTable, fullfile(outputFolder, "selected_angles.csv"));

practical = rmfield(results.practical, ...
    ["aggregateInterferenceDbm", "iOverNDb"]);
writetable(struct2table(practical), fullfile(outputFolder, ...
    "practical_selected_angles.csv"));

if results.config.output.writeDetailedTimeSeries
    timeSeries = table(results.selected.time, ...
        results.selected.aggregateInterferenceDbm, results.selected.iOverNDb, ...
        results.selected.dominantSatelliteIndex, ...
        results.selected.visibleSatelliteCount, ...
        results.selected.eligibleContributorCount, ...
        results.selected.candidateSatelliteCount, ...
        results.selected.effectiveContributorCount, ...
        results.practical.iOverNDb, VariableNames=["Time", ...
        "AggregateInterferenceDbm", "IOverNDb", "DominantSatelliteIndex", ...
        "VisibleSatelliteCount", "EligibleCandidateCount", ...
        "CandidateSatelliteCount", "EffectiveContributorCount", ...
        "PracticalSelectedIOverNDb"]);
    writetable(timeSeries, fullfile(outputFolder, "selected_time_series.csv"));
end

jsonConfig = results.config;
jsonConfig.simulation.startTime = char(results.config.simulation.startTime, ...
    "yyyy-MM-dd'T'HH:mm:ssXXX");
jsonConfig.simulation.durationSeconds = seconds(results.config.simulation.duration);
jsonConfig.simulation = rmfield(jsonConfig.simulation, "duration");
jsonText = jsonencode(jsonConfig, PrettyPrint=true);
fileId = fopen(fullfile(outputFolder, "configuration.json"), "w");
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", jsonText);
clear cleanup
end
